version: "3.9"

services:
  blib-export:
    build: .
    container_name: limelight-export-blib-service
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "${HOST_MACHINE_WEBAPP_PORT}:${WEBAPP_PORT}"
    labels:
      - traefik.enable=false
    environment:
      SPECTR_GET_SCAN_DATA_URL: ${SPECTR_GET_SCAN_DATA_URL}
      WEBAPP_PORT: ${WEBAPP_PORT}
      SPECTR_BATCH_SIZE: ${SPECTR_BATCH_SIZE}
      APP_WORKDIR: ${APP_WORKDIR}
      BLIB_DIR: ${BLIB_DIR}
      BLIB_EXEC_PATH: ${BLIB_EXEC_PATH}
    volumes:
      - type: bind
        source: ${HOST_MACHINE_BLIB_DIR}
        target: /data/app/blibdir
        read_only: false
      - type: bind
        source: ${HOST_MACHINE_WORKDIR}
        target: /data/app/workdir
        read_only: false
