
name: Release Workflow

on:
  release:
    types: [released]
    tags:
      - 'v*'

env:
  DOCKER_REPO: "mriffle/limelight-export-blib-service"

jobs:
  dockerhub:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta for webapp
        id: meta_webapp
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.DOCKER_REPO }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
      - name: Build and push webapp
        id: docker_build_webapp
        uses: docker/build-push-action@v2
        with:
          context: docker/webapp
          push: true
          tags: ${{ steps.meta_webapp.outputs.tags }}
